import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import type { ScanResult } from './scan-data';

export const generatePDFReport = (result: ScanResult) => {
  const doc = new jsPDF();
  const timestamp = format(new Date(result.timestamp), 'yyyy-MM-dd HH:mm:ss');

  // Title
  doc.setFontSize(22);
  doc.setTextColor(102, 126, 234); // Primary color
  doc.text('SECURESHIELD AI - Security Report', 14, 22);

  // Summary Table
  doc.setFontSize(12);
  doc.setTextColor(0, 0, 0);
  doc.text(`Target URL: ${result.url}`, 14, 35);
  doc.text(`Scan Date: ${timestamp}`, 14, 42);
  doc.text(`Security Score: ${result.score}/100`, 14, 49);
  doc.text(`Security Grade: ${result.grade}`, 14, 56);
  doc.text(`Detected Platform: ${result.hostingType}`, 14, 63);

  // Vulnerabilities Table
  const tableData = result.vulnerabilities.map((v) => [
    v.issue,
    v.severity.toUpperCase(),
    v.status.toUpperCase(),
    v.fixTime,
    v.description,
  ]);

  autoTable(doc, {
    startY: 75,
    head: [['Vulnerability', 'Severity', 'Status', 'Est. Fix Time', 'Description']],
    body: tableData,
    headStyles: { fillColor: [102, 126, 234] },
    alternateRowStyles: { fillColor: [245, 247, 255] },
  });

  // Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text(
      'Generated by SECURESHIELD AI - Global Website Protection',
      doc.internal.pageSize.width / 2,
      doc.internal.pageSize.height - 10,
      { align: 'center' }
    );
  }

  doc.save(`security-report-${result.url.replace(/[^a-z0-9]/gi, '-')}.pdf`);
};
